# Generated by Django 5.0.14 on 2025-06-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutsection",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="about/"),
        ),
    ]
